version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
build:
  verbosity: minimal
  

after_build:
- cmd: mkdir %APPVEYOR_BUILD_FOLDER%\DnD-WrathOfSilumgar
- cmd: copy "%APPVEYOR_BUILD_FOLDER%\D&D Wrath of Silumgar\Release\D&D Wrath of Silumgar.exe" %APPVEYOR_BUILD_FOLDER%\DnD-WrathOfSilumgar
- cmd: xcopy "%APPVEYOR_BUILD_FOLDER%\D&D Wrath of Silumgar\Game" %APPVEYOR_BUILD_FOLDER%\DnD-WrathOfSilumgar /e /i /h /y
- cmd: move %APPVEYOR_BUILD_FOLDER%\README.md %APPVEYOR_BUILD_FOLDER%\DnD-WrathOfSilumgar
- 7z a DnD-WrathOfSilumgar.zip %APPVEYOR_BUILD_FOLDER%\DnD-WrathOfSilumgar

artifacts:
- path: DnD-WrathOfSilumgar.zip
